export const cardListLeft = [
  {
    category: "housekeeping",
    name: "Check Mailbox",
    imageSrc: "/icons/mailbox.png",
    imageAlt: "mailbox",
    index: 0,
  },
  {
    category: "housekeeping",
    name: "Grocery Shopping",
    imageSrc: "icons/shopping.png",
    imageAlt: "shopping",
    index: 1,
  },
  {
    category: "housekeeping",
    name: "Invite Friends Over",
    imageSrc: "/icons/house.png",
    imageAlt: "house",
    index: 2,
  },
  {
    category: "housekeeping",
    name: "Grab Takeout Food",
    imageSrc: "/icons/hamburger.png",
    imageAlt: "hamburger",
    index: 3,
  },
  {
    category: "housekeeping",
    name: "Open a Package",
    imageSrc: "/icons/package.png",
    imageAlt: "package",
    index: 4,
  },
  {
    category: "job",
    name: "In-person Meeting",
    imageSrc: "/icons/meeting-room.png",
    imageAlt: "meeting-room",
    index: 5,
  },
  {
    category: "job",
    name: "Meet a Patient",
    imageSrc: "/icons/recovery.png",
    imageAlt: "recovery",
    index: 6,
  },
  {
    category: "job",
    name: "Interview Someone",
    imageSrc: "/icons/interview.png",
    imageAlt: "interview",
    index: 7,
  },
  {
    category: "job",
    name: "Working Alone",
    imageSrc: "/icons/working.png",
    imageAlt: "working",
    index: 8,
  },
  {
    category: "job",
    name: "Coworking",
    imageSrc: "/icons/coworking.png",
    imageAlt: "coworking",
    index: 9,
  },
  {
    category: "transportation",
    name: "Bus",
    imageSrc: "/icons/bus.png",
    imageAlt: "bus",
    index: 10,
  },
  {
    category: "transportation",
    name: "Subway",
    imageSrc: "/icons/Subway.png",
    imageAlt: "subway",
    index: 11,
  },
  {
    category: "transportation",
    name: "Uber",
    imageSrc: "/icons/uber-taxi.png",
    imageAlt: "uber-taxi",
    index: 12,
  },
  {
    category: "transportation",
    name: "Drive alone",
    imageSrc: "/icons/car.png",
    imageAlt: "car",
    index: 13,
  },
  {
    category: "transportation",
    name: "Pumping Gasoline",
    imageSrc: "/icons/gasoline.png",
    imageAlt: "gasoline",
    index: 14,
  },
  {
    category: "entertainment",
    name: "Movie at Theater",
    imageSrc: "/icons/theater.png",
    imageAlt: "theater",
    index: 15,
  },
  {
    category: "entertainment",
    name: "Golf",
    imageSrc: "icons/golf.png",
    imageAlt: "golf",
    index: 16,
  },
  {
    category: "entertainment",
    name: "Camping",
    imageSrc: "/icons/camping.png",
    imageAlt: "camping",
    index: 17,
  },
  {
    category: "entertainment",
    name: "Go to a Bar",
    imageSrc: "/icons/bar.png",
    imageAlt: "bar",
    index: 18,
  },
  {
    category: "entertainment",
    name: "Go to Beach",
    imageSrc: "/icons/beach.png",
    imageAlt: "beach",
    index: 19,
  },
  {
    category: "miscellaneous",
    name: "Public Restroom",
    imageSrc: "/icons/toilet.png",
    imageAlt: "toilet",
    index: 20,
  },
  {
    category: "miscellaneous",
    name: "Restaurant Dine-in",
    imageSrc: "icons/waiter.png",
    imageAlt: "waiter",
    index: 21,
  },
  {
    category: "miscellaneous",
    name: "Church Events",
    imageSrc: "/icons/church.png",
    imageAlt: "church",
    index: 22,
  },
  {
    category: "miscellaneous",
    name: "Visit Nursing Home",
    imageSrc: "/icons/elder.png",
    imageAlt: "elder",
    index: 23,
  },
  {
    category: "miscellaneous",
    name: "Staying at Hotel",
    imageSrc: "/icons/bed.png",
    imageAlt: "bed",
    index: 24,
  },
];

export const cardListRight = [
  {
    category: "housekeeping",
    name: "House Cleaning",
    imageSrc: "/icons/vaccum.png",
    imageAlt: "vaccum",
    index: 25,
  },
  {
    category: "housekeeping",
    name: "House Moving",
    imageSrc: "/icons/truck.png",
    imageAlt: "truck",
    index: 26,
  },
  {
    category: "housekeeping",
    name: "Yardwork",
    imageSrc: "/icons/lawnmover.png",
    imageAlt: "lawnmover",
    index: 27,
  },
  {
    category: "housekeeping",
    name: "Walk a Dog",
    imageSrc: "/icons/dog.png",
    imageAlt: "dog",
    index: 28,
  },
  {
    category: "housekeeping",
    name: "Use Public Laundry",
    imageSrc: "/icons/laundry.png",
    imageAlt: "laundry",
    index: 29,
  },
  {
    category: "job",
    name: "Lunch at Cafeteria",
    imageSrc: "/icons/cafeteria.png",
    imageAlt: "cafeteria",
    index: 30,
  },
  {
    category: "job",
    name: "Video Conference",
    imageSrc: "/icons/video-conference.png",
    imageAlt: "video-conference",
    index: 31,
  },
  {
    category: "transportation",
    name: "Drive w/ Passengers",
    imageSrc: "/icons/door-ajar.png",
    imageAlt: "door-ajar",
    index: 32,
  },
  {
    category: "transportation",
    name: "Walk",
    imageSrc: "/icons/walking.png",
    imageAlt: "walking",
    index: 33,
  },
  {
    category: "transportation",
    name: "Bike",
    imageSrc: "/icons/bike.png",
    imageAlt: "bike",
    index: 34,
  },
  {
    category: "transportation",
    name: "Travel by Plane",
    imageSrc: "/icons/plane.png",
    imageAlt: "plane",
    index: 35,
  },
  {
    category: "entertainment",
    name: "Shopping at Mall",
    imageSrc: "/icons/shopping-mall.png",
    imageAlt: "shopping-mall",
    index: 36,
  },
  {
    category: "entertainment",
    name: "Tennis",
    imageSrc: "icons/tennis.png",
    imageAlt: "tennis",
    index: 37,
  },
  {
    category: "entertainment",
    name: "Basketball/Football",
    imageSrc: "/icons/basketball.png",
    imageAlt: "basketball",
    index: 38,
  },
  {
    category: "entertainment",
    name: "Concerts",
    imageSrc: "/icons/stage.png",
    imageAlt: "stage",
    index: 39,
  },
  {
    category: "entertainment",
    name: "Backyard Barbecue",
    imageSrc: "/icons/souvla.png",
    imageAlt: "souvla",
    index: 40,
  },
  {
    category: "miscellaneous",
    name: "Attend a Wedding",
    imageSrc: "/icons/wedding.png",
    imageAlt: "wedding",
    index: 41,
  },
  {
    category: "miscellaneous",
    name: "Shaking Hands",
    imageSrc: "icons/handshake.png",
    imageAlt: "handshake",
    index: 42,
  },
  {
    category: "miscellaneous",
    name: "Workout at Gym",
    imageSrc: "/icons/gym.png",
    imageAlt: "gym",
    index: 43,
  },
  {
    category: "miscellaneous",
    name: "Visit Library",
    imageSrc: "/icons/library.png",
    imageAlt: "library",
    index: 44,
  },
  {
    category: "miscellaneous",
    name: "Stay in Crowds",
    imageSrc: "/icons/crowd.png",
    imageAlt: "crowd",
    index: 45,
  },
];
